FROM hexpm/elixir:1.14.2-erlang-25.1.2-alpine-3.16.2

ENV TZ America/Sao_Paulo
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
ENV LC_ALL en_US.UTF-8

RUN apk add --update --no-cache \
    inotify-tools \
    alpine-sdk tzdata bash xz \
    && cp /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime \
    && echo "America/Sao_Paulo" > /etc/timezone

WORKDIR /app

EXPOSE 4000

ENTRYPOINT [ "./entrypoint.dev.sh" ]
