version: "3"

services:
  postgres15:
    image: postgres:15.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: postgres -c max_connections=999
    volumes:
      - postgres15:/var/lib/postgresql/data

volumes:
  postgres15:
